import type { FaqItem } from "@/components/site/faq";

// FAQ content extracted verbatim from the Webflow capture.
// Answers are our own trusted static content (rendered via innerHTML).
export const FAQ_ITEMS: FaqItem[] = [
  { q: "What is ecommerce acceleration?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>Ecommerce acceleration is a focused program for improving an online store’s strategy, customer experience, technology, content, and conversion performance. ZINC identifies the highest-impact opportunities, then designs and implements the changes needed to grow efficiently.</p></div></div>` },
  { q: "Which ecommerce platforms does ZINC support?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>ZINC works with Shopify, Shopify Plus, BigCommerce, and connected ecommerce systems. Platform recommendations depend on product complexity, integrations, internal workflows, growth goals, and the experience customers need.</p></div></div>` },
  { q: "How can AI improve an ecommerce store?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>AI can improve product discovery, merchandising, content production, personalization, customer support, and operational workflows. ZINC prioritizes practical uses that improve the shopping experience or reduce repetitive work instead of adding technology without a measurable purpose.</p></div></div>` },
  { q: "Can ZINC connect our ERP, CRM, and marketing tools?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>Yes. ZINC plans and implements integrations across ecommerce platforms, ERP and inventory systems, CRM, email marketing, analytics, and other third-party tools. The integration scope is defined around reliable data flow and the team’s operating requirements.</p></div></div>` },
  { q: "How long does an ecommerce project take?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>Timing depends on the store, platform, integrations, catalog, and migration requirements. After an initial assessment, ZINC provides a phased plan with the expected schedule, responsibilities, and measurable launch goals.</p></div></div>` },
];
