#!/usr/bin/env python3
"""Componentize a captured Webflow page into Next.js source.
Usage: python3 scripts/componentize-page.py solutions/website-design-development
Emits src/app/<page>/{content.tsx,faq-items.ts,page.css} + metadata JSON to stdout.
page.tsx is written by hand (metadata + shell wiring)."""
import io, re, sys, glob, json, os

page = sys.argv[1]
html_path = f"public/_wf/{page}.html"
# the homepage routes at / via a route group
out_dir = "src/app/(home)" if page == "index" else f"src/app/{page}"
os.makedirs(out_dir, exist_ok=True)
s = io.open(html_path, encoding="utf-8").read()
_ix2 = io.open(glob.glob("public/wf/*schunk.0a294da0ce97949d.js")[0], encoding="utf-8", errors="ignore").read()
import re as _re
_events = _re.findall(r'eventTypeId:"[A-Z_]+"[^\0]*?actionListId:"(a[-\d]*)"[^\0]*?target:\{id:"[^"|]+\|([^"]+)"', _ix2)
_wid_action = {}
for _al, _wid in _events:
    _t = _re.search(r'"%s":\{id:"%s",title:"([^"]*)"' % (_al, _al), _ix2)
    if _t: _wid_action.setdefault(_wid, _t.group(1))
body = s[s.find("<body"):s.find("</body")]

# ---------- main content (nav and footer replaced by the shell) ----------
main_start = body.rfind("<", 0, body.find('class="main-wrapper"'))
foot_start = body.rfind("<footer", 0, body.find("footer3_component"))
main = body[main_start:foot_start]
# Style blocks inside main (some pages embed the global utility styles
# there) are captured separately into page.css — strip them from markup
# so JSX conversion never sees CSS braces.
main = re.sub(r'<style[^>]*>.*?</style>', '', main, flags=re.S)
main = re.sub(r'<script[^>]*type="application/json"[^>]*>.*?</script>', '', main, flags=re.S)
_scripts_in_main = re.findall(r'<script[^>]*>', main)
if _scripts_in_main:
    print("NOTE: non-json scripts in main:", _scripts_in_main[:3], file=sys.stderr)
main = re.sub(r'<script[^>]*>.*?</script>', '', main, flags=re.S)

classes = set()
for m in re.finditer(r'class="([^"]+)"', main):
    classes.update(m.group(1).split())
ids = set(re.findall(r'id="([^"]+)"', main))
if "w-slider" in main:
    classes.update(["w-slider-dot", "w-slider-nav", "w-active", "w-round", "w-slider-nav-invert"])

# ---------- CSS subset extraction ----------
css = "".join(io.open(f, encoding="utf-8", errors="ignore").read() for f in sorted(glob.glob("public/wf/*.css")))
rules = []
def parse(block, media=""):
    i = 0
    while i < len(block):
        at = block.find("{", i)
        if at == -1: break
        sel = block[i:at].strip()
        depth = 1; j = at + 1
        while j < len(block) and depth:
            if block[j] == "{": depth += 1
            elif block[j] == "}": depth -= 1
            j += 1
        inner = block[at+1:j-1]
        if sel.startswith("@media"): parse(inner, sel)
        elif sel.startswith("@"): pass
        else: rules.append((media, sel, inner.strip()))
        i = j
parse(css)

cls_re = re.compile(r'\.((?:[\w-]|\\.)+)')
id_re = re.compile(r'#((?:[\w-]|\\.)+)')
ELEMENTS = {"html","body","h1","h2","h3","h4","h5","h6","p","a","ul","ol","li","img","figure","figcaption","blockquote","strong","em","div",":root","*",
            "form","label","input","textarea","select","button","fieldset","legend","option","optgroup"}
def part_applies(part):
    scs = {c.replace("\\", "") for c in cls_re.findall(part)}
    sids = {c.replace("\\", "") for c in id_re.findall(part)}
    if sids: return bool(sids & ids)
    if scs: return bool(scs & classes)
    base = re.split(r'[\s:>+~\[]', part.strip())[0] or part.strip()
    return base in ELEMENTS or part.strip().startswith(":root") or part.strip() == "*"

kept = []
for media, sel, rbody in rules:
    parts = [p.strip() for p in sel.split(",")]
    applicable = [p for p in parts if part_applies(p)]
    if applicable: kept.append((media, ", ".join(applicable), rbody))

# ---------- page-embedded style blocks ----------
blocks = re.findall(r'<style[^>]*>(.*?)</style>', s, re.S)
embedded, seen = [], set()
for b in blocks:
    b = b.strip()
    if not b or b in seen: continue
    seen.add(b)
    if "gsap-js" in b and "data-gsap-lines" in b: continue          # reveal layer (shared)
    if "--font-from" in b and "--coefficient" in b: continue        # fluid root (site.css)
    sels = re.findall(r'([^{}/@]+)\{', re.sub(r'/\*.*?\*/', '', b, flags=re.S))
    sels = [x.strip() for x in sels if x.strip()]
    if sels and all("navbar2_" in x for x in sels): continue        # nav shell handles
    # Author errors in the capture: mid-file @import (often missing the
    # semicolon) — browsers ignore them, PostCSS errors. Strip.
    b = re.sub(r'@import[^;\n]*;?', '', b)
    embedded.append(b)

# ---------- assemble page.css ----------
out = io.StringIO()
out.write('/* Generated by scripts/componentize-page.py for /%s.\n' % page)
out.write('   Auto-extracted Webflow CSS subset + page-embedded style blocks. */\n\n')
out.write('@font-face {\n  font-family: "Bdogrotesk Bf 648 A 656 F 04 A 15";\n  src: url("/fonts/BDOGrotesk-DemiBold.otf") format("opentype");\n  font-weight: 600;\n  font-style: normal;\n  font-display: swap;\n}\n\n')
cur = None
for media, sel, rbody in kept:
    if media != cur:
        if cur: out.write("}\n")
        if media: out.write(f"{media} {{\n")
        cur = media
    out.write(("  " if media else "") + f"{sel} {{ {rbody} }}\n")
if cur: out.write("}\n")
out.write("\n/* ---- page-embedded style blocks (verbatim) ---- */\n")
out.write("\n\n".join(embedded))
io.open(f"{out_dir}/page.css", "w").write(out.getvalue())

# ---------- FAQ extraction ----------
def find_matching_div(t, start):
    i = t.find('>', start) + 1
    depth = 1
    while depth:
        m = re.search(r'<div\b|</div>', t[i:])
        if not m: raise ValueError('unbalanced')
        i += m.end()
        depth += 1 if m.group(0) != '</div>' else -1
    return i

faq_variants = {}   # prefix -> [(question_inner, answer_inner)]
for prefix in ["faq2", "faq3"]:
    search = 0
    while True:
        fl = main.find(f'class="{prefix}_list"', search)
        if fl == -1: break
        fl_open = main.rfind('<div', 0, fl)
        fl_end = find_matching_div(main, fl_open)
        fb = main[fl_open:fl_end]
        entries = faq_variants.setdefault(prefix, [])
        pos = 0
        while True:
            a = fb.find(f'class="{prefix}_accordion"', pos)
            if a == -1: break
            a_open = fb.rfind('<div', 0, a)
            a_end = find_matching_div(fb, a_open)
            acc = fb[a_open:a_end]
            # question inner = everything inside the question div (text + icon)
            q_i = acc.find(f'class="{prefix}_question"')
            q_open = acc.rfind('<div', 0, q_i)
            q_end = find_matching_div(acc, q_open)
            q_inner = acc[acc.find('>', q_open) + 1:q_end - len('</div>')]
            ans_i = acc.find(f'class="{prefix}_answer"')
            ans_open = acc.rfind('<div', 0, ans_i)
            ans_end = find_matching_div(acc, ans_open)
            ans_inner = acc[acc.find('>', ans_open) + 1:ans_end - len('</div>')]
            # collapsed initial state is encoded as an inline height:0 style
            default_open = 'style="width:100%;height:0px"' not in acc
            entries.append((q_inner.strip(), ans_inner.strip(), default_open))
            pos = a_end
        tag_end = fb.find('>') + 1
        marker = f'<FaqList prefix="{prefix}" items={{{prefix.upper()}_ITEMS}} />'
        new_block = fb[:tag_end] + "\n" + marker + "\n</div>"
        main = main[:fl_open] + new_block + main[fl_end:]
        search = fl_open + len(new_block)
items = [x for v in faq_variants.values() for x in v]

ts = io.StringIO()
ts.write('import type { FaqEntry } from "@/components/site/faq-list";\n\n')
ts.write('// FAQ content extracted verbatim from the Webflow capture.\n')
def esc(t):
    return t.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
for prefix, entries in faq_variants.items():
    ts.write(f'export const {prefix.upper()}_ITEMS: FaqEntry[] = [\n')
    for q, a, dopen in entries:
        extra = ", defaultOpen: true" if dopen else ""
        ts.write(f'  {{ question: `{esc(q)}`, answer: `{esc(a)}`{extra} }},\n')
    ts.write('];\n\n')
io.open(f"{out_dir}/faq-items.ts", "w").write(ts.getvalue())

# ---------- IX2 artifact cleanup + JSX conversion ----------
main = re.sub(r'\s*data-w-id="[^"]*"', '', main)
main = re.sub(r'\s*style="width:100%;height:0px"', '', main)
def fade_sub(m):
    tag = m.group(0)
    widm = re.search(r'data-w-id="([^"]+)"', tag)
    title = _wid_action.get(widm.group(1), "") if widm else ""
    variant = ""
    if "0.8" in title: variant = " fade-up-08"
    elif title.endswith(" 1") or "slide in 1" in title: variant = " fade-up-10"
    tag = re.sub(r'\s*style="[^"]*"', '', tag)
    if 'class="' in tag:
        tag = re.sub(r'class="([^"]*)"', lambda c: f'class="{c.group(1)} fade-up{variant}"', tag, count=1)
    return tag
main = re.sub(r'<(?:p|div|h\d)[^>]*style="[^"]*transform:translate3d[^"]*opacity:0[^"]*"[^>]*>', fade_sub, main)
main = re.sub(r'<(?:p|div|h\d)[^>]*style="[^"]*opacity:0[^"]*transform:translate3d[^"]*"[^>]*>', fade_sub, main)
assert 'transform:translate3d' not in main, "IX2 inline style remains"
leftovers = re.findall(r'style="[^"]{0,80}"', main)
if leftovers:
    print("NOTE: remaining inline styles (verify intentional):", leftovers[:5], file=sys.stderr)

text_only = re.sub(r'<[^>]+>', ' ', main)
assert '{' not in text_only and '}' not in text_only, "curly braces in text"
main = re.sub(r'<!--.*?-->', '', main, flags=re.S)
# numeric attrs -> JSX expressions; boolean attrs -> bare
main = re.sub(r'\b(maxLength|maxlength)="(\d+)"', r'maxLength={\2}', main)
main = re.sub(r'\btabindex="(-?\d+)"', r'tabIndex={\1}', main)
main = re.sub(r'\b(required|disabled|checked|multiple|selected|readonly)=""', lambda m: {"readonly": "readOnly"}.get(m.group(1), m.group(1)), main)
# IX2 opacity:0 initial states -> fade-in class (ix-fade.tsx reveals)
def ix_fade_sub(m):
    tag = m.group(0).replace(m.group(1), "")
    if 'class="' in tag:
        tag = re.sub(r'class="([^"]*)"', lambda c: f'class="{c.group(1)} ix-fade"', tag, count=1)
    else:
        tag = tag[:-1].rstrip("/") + ' class="ix-fade"' + ("/>" if tag.endswith("/>") else ">")
    return tag
main = re.sub(r'<[a-zA-Z][^>]*?(\s*style="opacity:0")[^>]*>', ix_fade_sub, main)

# remaining inline styles -> JSX style objects (e.g. Webflow's visually-
# hidden checkbox inputs)
def style_obj(m):
    decls = [d.strip() for d in m.group(1).split(";") if d.strip()]
    parts = []
    for d in decls:
        k, _, v = d.partition(":")
        k = k.strip(); v = v.strip()
        kk = re.sub(r'-([a-z])', lambda c: c.group(1).upper(), k)
        parts.append(f'{kk}:"{v}"')
    return 'style={{' + ",".join(parts) + '}}'
main = re.sub(r'style="([^"]*)"', style_obj, main)
# for= only valid on <label>; Webflow puts it on spans — drop it there
main = re.sub(r'(<span[^>]*?)\s+for="[^"]*"', r'\1', main)
for a, b in [('class="', 'className="'), ('srcset="', 'srcSet="'), ('fill-rule=', 'fillRule='),
             ('clip-rule=', 'clipRule='), ('stroke-width=', 'strokeWidth='), ('tabindex=', 'tabIndex='),
             ('for="', 'htmlFor="'), ('autocomplete=', 'autoComplete='), ('maxlength=', 'maxLength='),
             ('novalidate', 'noValidate'), ('autofocus', 'autoFocus'),
             ('xmlns:xlink=', 'xmlnsXlink='), ('xlink:href=', 'xlinkHref='), ('xml:space=', 'xmlSpace=')]:
    main = main.replace(a, b)

comp = io.StringIO()
comp.write('/* eslint-disable @next/next/no-img-element */\n')
comp.write('// Markup converted mechanically from the Webflow capture (Phase B).\n')
comp.write('import { FaqList } from "@/components/site/faq-list";\n')
if faq_variants:
    names = ", ".join(f"{p.upper()}_ITEMS" for p in faq_variants)
    comp.write(f'import {{ {names} }} from "./faq-items";\n')
comp.write('\n')
# balance: some pages nest the footer inside <main>, so the slice can
# leave wrapper elements unclosed — append the missing closers.
VOID = {"br","img","hr","input","meta","link","source","area","base","col","embed","track","wbr"}
stack = []
for tm in re.finditer(r'<(/?)([a-zA-Z][a-zA-Z0-9]*)((?:"[^"]*"|[^">])*)>', main):
    close, tag, _attrs = tm.groups()
    self_closed = tm.group(0).rstrip(">").rstrip().endswith("/")
    if tag.lower() in VOID or self_closed: continue
    if close:
        if stack and stack[-1] == tag: stack.pop()
    else:
        stack.append(tag)
closers = "".join(f"</{t}>" for t in reversed(stack))
if closers:
    print("NOTE: auto-closing sliced wrappers:", closers, file=sys.stderr)

comp.write('export function PageContent() {\n  return (\n    <>\n')
comp.write(main.strip() + closers)
comp.write('\n    </>\n  );\n}\n')
io.open(f"{out_dir}/content.tsx", "w").write(comp.getvalue())

# ---------- counters bundle ----------
counter_bundle = None
if "new PureCounter" in s:
    _ci = s.find("purecounter_vanilla.js")
    _cs = s.find("<script>", _ci)
    _ce = s.find("</script>", _cs)
    _init = s[_cs + 8:_ce]
    _vendor = io.open("public/vendor/purecounter_vanilla.js").read()
    _slug = page.replace("/", "-")
    counter_bundle = f"/js/{_slug}-counters.js"
    io.open(f"public/js/{_slug}-counters.js", "w").write(_vendor + "\n" + _init)

# ---------- metadata for page.tsx ----------
head = s.split("</head>")[0]
def g(*pats):
    for p in pats:
        m = re.search(p, head)
        if m: return m.group(1)
    return None
meta = {
    "title": g(r"<title>([^<]*)</title>"),
    "description": g(r'content="([^"]*)" name="description"', r'name="description" content="([^"]*)"'),
    "ogImage": g(r'content="([^"]*)" property="og:image"', r'property="og:image" content="([^"]*)"'),
    "canonical": g(r'<link href="([^"]*)" rel="canonical"', r'rel="canonical" href="([^"]*)"'),
    "faqCount": len(items),
    "hasParallax": "layout414_image-list" in s,
    "hasMarquee": "logo3_component" in s,
}
meta["hasSlider"] = 'w-slider"' in s or "w-slider " in s
meta["hasForm"] = "<form" in s
meta["hasIxFade"] = "ix-fade" in main
meta["hasTimeline"] = "layout121_progress-bar" in s
meta["counterBundle"] = counter_bundle
print(json.dumps(meta, indent=1))

# ---------- page.tsx ----------
import html as _html
title = _html.unescape(meta["title"] or "")
desc = _html.unescape(meta["description"] or "")
canonical = meta["canonical"] or f"https://www.wearezinc.com/{page}"
comp_name = "".join(w.capitalize() for w in re.split(r"[-/]", page)) + "Page"
extra_imports, extra_jsx, extra_scripts = [], [], []
if meta["hasParallax"]:
    extra_imports.append('import { StripParallax } from "@/components/site/strip-parallax";')
    extra_jsx.append("      <StripParallax />")
if meta["hasSlider"]:
    extra_imports.append('import { SliderBehavior } from "@/components/site/slider-behavior";')
    extra_jsx.append("      <SliderBehavior />")
if meta["hasTimeline"]:
    extra_imports.append('import { TimelineProgress } from "@/components/site/timeline-progress";')
    extra_jsx.append("      <TimelineProgress />")
if meta.get("hasIxFade"):
    extra_imports.append('import { IxFade } from "@/components/site/ix-fade";')
    extra_jsx.append("      <IxFade />")
if counter_bundle:
    extra_scripts.append(f'      <Script src="{counter_bundle}" strategy="afterInteractive" />')
if meta["hasForm"]:
    extra_scripts.append('      <Script src="/js/zinc-forms.js" strategy="afterInteractive" />')

page_tsx = f"""import type {{ Metadata }} from "next";
import Script from "next/script";
import {{ Navbar }} from "@/components/site/navbar";
import {{ Footer }} from "@/components/site/footer";
import {{ SiteAnalytics }} from "@/components/site/analytics";
{chr(10).join(extra_imports)}
import {{ PageContent }} from "./content";
import "@/components/site/site.css";
import "@/components/site/page-animations.css";
import "./page.css";

// Generated by scripts/componentize-page.py from the Webflow capture.

const TITLE = {json.dumps(title)};
const DESCRIPTION = {json.dumps(desc)};

export const metadata: Metadata = {{
  title: TITLE,
  description: DESCRIPTION,
  alternates: {{ canonical: {json.dumps(canonical)} }},
  openGraph: {{
    title: TITLE,
    description: DESCRIPTION,
    type: "website",
    images: [{json.dumps(meta["ogImage"] or "https://www.wearezinc.com/wf/695bda13c7c5d5a8fcdb44f2_home_header1.webp")}],
  }},
  twitter: {{ card: "summary_large_image", title: TITLE, description: DESCRIPTION }},
}};

const ORG_SCHEMA = {{
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "ZINC",
  url: "https://www.wearezinc.com",
  logo: "https://www.wearezinc.com/wf/695bda13c7c5d5a8fcdb45fd_zinc_webclip.png",
  description:
    "ZINC is an AI-driven digital strategy and design agency: AI enablement, answer engine optimization (AEO), web design and development, ecommerce, branding, and marketing systems.",
}};

export default function {comp_name}() {{
  return (
    <div className="site">
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      <link
        href="https://fonts.googleapis.com/css2?family=Geist:wght@300;400;500;600;700&family=Geist+Mono:wght@300;400;500;600;700&display=swap"
        rel="stylesheet"
      />
      <script
        dangerouslySetInnerHTML={{{{ __html: "document.documentElement.classList.add('gsap-js');" }}}}
      />
      <Navbar />
      <PageContent />
{chr(10).join(extra_jsx)}
      <Footer />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{{{ __html: JSON.stringify(ORG_SCHEMA) }}}}
      />
      <Script src="/js/reveal.js" strategy="afterInteractive" />
{chr(10).join(extra_scripts)}
      <SiteAnalytics />
    </div>
  );
}}
"""
io.open(f"{out_dir}/page.tsx", "w").write(page_tsx)
