#!/usr/bin/env python3
"""Componentize a captured Webflow page into Next.js source.
Usage: python3 scripts/componentize-page.py solutions/website-design-development
Emits src/app/<page>/{content.tsx,faq-items.ts,page.css} + metadata JSON to stdout.
page.tsx is written by hand (metadata + shell wiring)."""
import io, re, sys, glob, json, os

page = sys.argv[1]
html_path = f"public/_wf/{page}.html"
out_dir = f"src/app/{page}"
os.makedirs(out_dir, exist_ok=True)
s = io.open(html_path, encoding="utf-8").read()
body = s[s.find("<body"):s.find("</body")]

# ---------- main content (nav and footer replaced by the shell) ----------
main_start = body.rfind("<", 0, body.find('class="main-wrapper"'))
foot_start = body.rfind("<footer", 0, body.find("footer3_component"))
main = body[main_start:foot_start]

classes = set()
for m in re.finditer(r'class="([^"]+)"', main):
    classes.update(m.group(1).split())
ids = set(re.findall(r'id="([^"]+)"', main))

# ---------- CSS subset extraction ----------
css = "".join(io.open(f, encoding="utf-8", errors="ignore").read() for f in sorted(glob.glob("public/wf/*.css")))
rules = []
def parse(block, media=""):
    i = 0
    while i < len(block):
        at = block.find("{", i)
        if at == -1: break
        sel = block[i:at].strip()
        depth = 1; j = at + 1
        while j < len(block) and depth:
            if block[j] == "{": depth += 1
            elif block[j] == "}": depth -= 1
            j += 1
        inner = block[at+1:j-1]
        if sel.startswith("@media"): parse(inner, sel)
        elif sel.startswith("@"): pass
        else: rules.append((media, sel, inner.strip()))
        i = j
parse(css)

cls_re = re.compile(r'\.((?:[\w-]|\\.)+)')
id_re = re.compile(r'#((?:[\w-]|\\.)+)')
ELEMENTS = {"html","body","h1","h2","h3","h4","h5","h6","p","a","ul","ol","li","img","figure","figcaption","blockquote","strong","em","div",":root","*"}
def part_applies(part):
    scs = {c.replace("\\", "") for c in cls_re.findall(part)}
    sids = {c.replace("\\", "") for c in id_re.findall(part)}
    if sids: return bool(sids & ids)
    if scs: return bool(scs & classes)
    base = re.split(r'[\s:>+~\[]', part.strip())[0] or part.strip()
    return base in ELEMENTS or part.strip().startswith(":root") or part.strip() == "*"

kept = []
for media, sel, rbody in rules:
    parts = [p.strip() for p in sel.split(",")]
    applicable = [p for p in parts if part_applies(p)]
    if applicable: kept.append((media, ", ".join(applicable), rbody))

# ---------- page-embedded style blocks ----------
blocks = re.findall(r'<style[^>]*>(.*?)</style>', s, re.S)
embedded, seen = [], set()
for b in blocks:
    b = b.strip()
    if not b or b in seen: continue
    seen.add(b)
    if "gsap-js" in b and "data-gsap-lines" in b: continue          # reveal layer (shared)
    if "--font-from" in b and "--coefficient" in b: continue        # fluid root (site.css)
    sels = re.findall(r'([^{}/@]+)\{', re.sub(r'/\*.*?\*/', '', b, flags=re.S))
    sels = [x.strip() for x in sels if x.strip()]
    if sels and all("navbar2_" in x for x in sels): continue        # nav shell handles
    # Author errors in the capture: mid-file @import (often missing the
    # semicolon) — browsers ignore them, PostCSS errors. Strip.
    b = re.sub(r'@import[^;\n]*;?', '', b)
    embedded.append(b)

# ---------- assemble page.css ----------
out = io.StringIO()
out.write('/* Generated by scripts/componentize-page.py for /%s.\n' % page)
out.write('   Auto-extracted Webflow CSS subset + page-embedded style blocks. */\n\n')
out.write('@font-face {\n  font-family: "Bdogrotesk Bf 648 A 656 F 04 A 15";\n  src: url("/fonts/BDOGrotesk-DemiBold.otf") format("opentype");\n  font-weight: 600;\n  font-style: normal;\n  font-display: swap;\n}\n\n')
cur = None
for media, sel, rbody in kept:
    if media != cur:
        if cur: out.write("}\n")
        if media: out.write(f"{media} {{\n")
        cur = media
    out.write(("  " if media else "") + f"{sel} {{ {rbody} }}\n")
if cur: out.write("}\n")
out.write("\n/* ---- page-embedded style blocks (verbatim) ---- */\n")
out.write("\n\n".join(embedded))
io.open(f"{out_dir}/page.css", "w").write(out.getvalue())

# ---------- FAQ extraction ----------
def find_matching_div(t, start):
    i = t.find('>', start) + 1
    depth = 1
    while depth:
        m = re.search(r'<div\b|</div>', t[i:])
        if not m: raise ValueError('unbalanced')
        i += m.end()
        depth += 1 if m.group(0) != '</div>' else -1
    return i

items = []
if 'faq2_list' in main:
    fl = main.find('class="faq2_list"')
    fl_open = main.rfind('<div', 0, fl)
    fl_end = find_matching_div(main, fl_open)
    fb = main[fl_open:fl_end]
    pos = 0
    while True:
        a = fb.find('class="faq2_accordion"', pos)
        if a == -1: break
        a_open = fb.rfind('<div', 0, a)
        a_end = find_matching_div(fb, a_open)
        acc = fb[a_open:a_end]
        qm = re.search(r'faq2_question[^>]*>\s*<div[^>]*>(.*?)</div>', acc, re.S)
        ans_i = acc.find('class="faq2_answer"')
        ans_open = acc.rfind('<div', 0, ans_i)
        ans_end = find_matching_div(acc, ans_open)
        ans_inner = acc[acc.find('>', ans_open) + 1:ans_end - len('</div>')]
        items.append((qm.group(1).strip(), ans_inner.strip()))
        pos = a_end
    tag_end = fb.find('>') + 1
    main = main[:fl_open] + fb[:tag_end] + "\n<FaqItems items={FAQ_ITEMS} />\n</div>" + main[fl_end:]

ts = io.StringIO()
ts.write('import type { FaqItem } from "@/components/site/faq";\n\n')
ts.write('// FAQ content extracted verbatim from the Webflow capture.\n')
ts.write('export const FAQ_ITEMS: FaqItem[] = [\n')
for q, a in items:
    a_js = a.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
    q_js = q.replace('\\', '\\\\').replace('"', '\\"')
    ts.write(f'  {{ q: "{q_js}", a: `{a_js}` }},\n')
ts.write('];\n')
io.open(f"{out_dir}/faq-items.ts", "w").write(ts.getvalue())

# ---------- IX2 artifact cleanup + JSX conversion ----------
main = re.sub(r'\s*data-w-id="[^"]*"', '', main)
main = re.sub(r'\s*style="width:100%;height:0px"', '', main)
def fade_sub(m):
    tag = re.sub(r'\s*style="[^"]*"', '', m.group(0))
    return tag.replace('class="text-size-medium"', 'class="text-size-medium fade-up"')
main = re.sub(r'<p[^>]*style="[^"]*transform[^"]*"[^>]*>', fade_sub, main)
assert 'transform:translate3d' not in main, "IX2 inline style remains"
leftovers = re.findall(r'style="[^"]{0,80}"', main)
if leftovers:
    print("NOTE: remaining inline styles (verify intentional):", leftovers[:5], file=sys.stderr)

text_only = re.sub(r'<[^>]+>', ' ', main)
assert '{' not in text_only and '}' not in text_only, "curly braces in text"
main = re.sub(r'<!--.*?-->', '', main, flags=re.S)
for a, b in [('class="', 'className="'), ('srcset="', 'srcSet="'), ('fill-rule=', 'fillRule='),
             ('clip-rule=', 'clipRule='), ('stroke-width=', 'strokeWidth='), ('tabindex=', 'tabIndex=')]:
    main = main.replace(a, b)

comp = io.StringIO()
comp.write('/* eslint-disable @next/next/no-img-element */\n')
comp.write('// Markup converted mechanically from the Webflow capture (Phase B).\n')
comp.write('import { FaqItems } from "@/components/site/faq";\n')
comp.write('import { FAQ_ITEMS } from "./faq-items";\n\n')
comp.write('export function PageContent() {\n  return (\n    <>\n')
comp.write(main.strip())
comp.write('\n    </>\n  );\n}\n')
io.open(f"{out_dir}/content.tsx", "w").write(comp.getvalue())

# ---------- metadata for page.tsx ----------
head = s.split("</head>")[0]
def g(*pats):
    for p in pats:
        m = re.search(p, head)
        if m: return m.group(1)
    return None
meta = {
    "title": g(r"<title>([^<]*)</title>"),
    "description": g(r'content="([^"]*)" name="description"', r'name="description" content="([^"]*)"'),
    "ogImage": g(r'content="([^"]*)" property="og:image"', r'property="og:image" content="([^"]*)"'),
    "canonical": g(r'<link href="([^"]*)" rel="canonical"', r'rel="canonical" href="([^"]*)"'),
    "faqCount": len(items),
    "hasParallax": "layout414_image-list" in s,
    "hasMarquee": "logo3_component" in s,
}
print(json.dumps(meta, indent=1))
