#!/usr/bin/env python3
"""Extract the compiled-CSS subset + embedded styles for a template file.
Usage: extract-template-css.py src/templates/blog.html src/app/blog/page.css"""
import io, re, sys, glob

src, dest = sys.argv[1], sys.argv[2]
s = io.open(src, encoding="utf-8").read()
classes = set()
for m in re.finditer(r'class="([^"]+)"', s):
    classes.update(m.group(1).split())
ids = set(re.findall(r'id="([^"]+)"', s))

css = "".join(io.open(f, encoding="utf-8", errors="ignore").read() for f in sorted(glob.glob("public/wf/*.css")))
rules = []
def parse(block, media=""):
    i = 0
    while i < len(block):
        at = block.find("{", i)
        if at == -1: break
        sel = block[i:at].strip()
        depth = 1; j = at + 1
        while j < len(block) and depth:
            if block[j] == "{": depth += 1
            elif block[j] == "}": depth -= 1
            j += 1
        inner = block[at+1:j-1]
        if sel.startswith("@media"): parse(inner, sel)
        elif sel.startswith("@"): pass
        else: rules.append((media, sel, inner.strip()))
        i = j
parse(css)
cls_re = re.compile(r'\.((?:[\w-]|\\.)+)')
id_re = re.compile(r'#((?:[\w-]|\\.)+)')
ELEMENTS = {"html","body","h1","h2","h3","h4","h5","h6","p","a","ul","ol","li","img","figure","figcaption","blockquote","strong","em","div",":root","*",
            "form","label","input","textarea","select","button","fieldset","legend","option","optgroup"}
def part_applies(part):
    scs = {c.replace("\\", "") for c in cls_re.findall(part)}
    sids = {c.replace("\\", "") for c in id_re.findall(part)}
    if sids: return bool(sids & ids)
    if scs: return bool(scs & classes)
    base = re.split(r'[\s:>+~\[]', part.strip())[0] or part.strip()
    return base in ELEMENTS or part.strip().startswith(":root") or part.strip() == "*"
kept = []
for media, sel, rbody in rules:
    parts = [p.strip() for p in sel.split(",")]
    applicable = [p for p in parts if part_applies(p)]
    if applicable: kept.append((media, ", ".join(applicable), rbody))

blocks = re.findall(r'<style[^>]*>(.*?)</style>', s, re.S)
embedded, seen = [], set()
for b in blocks:
    b = b.strip()
    if not b or b in seen: continue
    seen.add(b)
    if "gsap-js" in b and "data-gsap-lines" in b: continue
    if "--font-from" in b and "--coefficient" in b: continue
    sels = re.findall(r'([^{}/@]+)\{', re.sub(r'/\*.*?\*/', '', b, flags=re.S))
    sels = [x.strip() for x in sels if x.strip()]
    if sels and all("navbar2_" in x for x in sels): continue
    b = re.sub(r'@import[^;\n]*;?', '', b)
    embedded.append(b)

out = io.StringIO()
out.write(f"/* Generated by scripts/extract-template-css.py from {src}. */\n\n")
out.write('@font-face {\n  font-family: "Bdogrotesk Bf 648 A 656 F 04 A 15";\n  src: url("/fonts/BDOGrotesk-DemiBold.otf") format("opentype");\n  font-weight: 600;\n  font-style: normal;\n  font-display: swap;\n}\n\n')
cur = None
for media, sel, rbody in kept:
    if media != cur:
        if cur: out.write("}\n")
        if media: out.write(f"{media} {{\n")
        cur = media
    out.write(("  " if media else "") + f"{sel} {{ {rbody} }}\n")
if cur: out.write("}\n")
out.write("\n" + "\n\n".join(embedded))
io.open(dest, "w").write(out.getvalue())
print(f"{dest}: {len(kept)} rules + {len(embedded)} embedded blocks")
