import type { FaqItem } from "@/components/site/faq";

// Answers are our own trusted static content (rendered via innerHTML).
export const FAQ_ITEMS: FaqItem[] = [
  { q: "Who is a migration right for?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>B2B and informational sites, roughly 20 to 300 pages, with lead forms, a blog, service pages, and CRM connections. Ecommerce stores, membership systems, and plugin-heavy applications need separate discovery. Sometimes staying put is the right answer, and we will say so.</p></div></div>` },
  { q: "Will we lose our rankings?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>URLs are preserved or mapped, metadata and indexability are validated, and the site is monitored after launch. Google itself anticipates some fluctuation after a site move. A careful process is the promise, not a guarantee.</p></div></div>` },
  { q: "How long does a migration take?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>Two numbers, stated separately. A working preview of representative pages takes days. Production launch is scoped around your content, integrations, and approvals, and both numbers appear in every quote.</p></div></div>` },
  { q: "Do we need a developer afterward?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>Not for day-to-day changes. Your team asks, reviews, and approves in Dispatch. ZINC stays on as operator, advisor, or escalation contact if you want us to.</p></div></div>` },
  { q: "Can you migrate a Webflow site?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>Yes. If Webflow still fits your team's workflow, we may recommend keeping it. If cost, code portability, agent access, or operational speed has become the constraint, we recreate the site on an open, agent-ready stack and preserve the design and content.</p></div></div>` },
  { q: "What happens to our CMS?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>It is retired. Content moves into the repository, or into a headless content backend if you need one. No more seats, plugins, or page-builder hosting.</p></div></div>` },
  { q: "What does it cost?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>A fixed-quote project after a short assessment. Every quote shows the one-time fee, inclusions, exclusions, acceptance criteria, launch estimate, stabilization period, recurring costs, and a full comparison with what you pay today.</p></div></div>` },
];
