import type { FaqItem } from "@/components/site/faq";

// Approved copy from the Sept 22, 2026 Dispatch messaging recommendations.
// Answers are our own trusted static content (rendered via innerHTML).
const wrap = (html: string) => `<div class="margin-bottom margin-small"><div class="max-width-large">${html}</div></div>`;

export const FAQ_ITEMS: FaqItem[] = [
  { q: "What is Dispatch?", a: wrap(`<p>Dispatch is the management layer for AI-powered websites. It sits above the coding agent, repository, and host to record who requested each change, what context shaped it, who approved it, what changed, and how to restore the prior version. It gives teams the visibility and control needed to let AI work on a real website.</p>`) },
  { q: "Does Dispatch replace our AI agent?", a: wrap(`<p>No. Dispatch is built around a bring-your-own-agent model. Your team can use agents such as Claude Code, Codex, or Gemini. Dispatch governs the requests, previews, approvals, attribution, and history around their work.</p>`) },
  { q: "Do we need to migrate our website to use Dispatch?", a: wrap(`<p>Not always. A compatible code-based website may be connected to Dispatch without a redesign or platform migration. If your current site is on a traditional CMS, ZINC can assess whether improving it in place or moving to an agent-ready architecture creates the stronger business case.</p>`) },
  { q: "Is it safe to let AI change our production website?", a: wrap(`<p>AI website work needs controls. Dispatch keeps work on a branch, provides a preview before release, assigns approvals by role and risk, records every action, and supports one-click restore for covered website changes. ZINC also defines the operating process, responsibilities, and exceptions with your team.</p>`) },
  { q: "Will we lose control of our website or become locked in?", a: wrap(`<p>Your website code, content, and history stay in your repository and host. ZINC documents ownership, access, third-party services, and handoff responsibilities in the project scope. Dispatch provides the management layer without becoming the place where the website itself must live.</p>`) },
  { q: "Can ZINC preserve our current design and content?", a: wrap(`<p>Yes. A migration can retain the agreed design and content. ZINC inventories pages, URLs, forms, analytics, and integrations; identifies what can carry over; and flags what needs to be rebuilt or improved before scope is approved.</p>`) },
  { q: "What about SEO and AEO?", a: wrap(`<p>ZINC plans URL continuity, redirects, metadata, internal links, and launch checks, then monitors performance after cutover. Search rankings can fluctuate after a migration, so unchanged rankings should not be promised. Dispatch also scores pages for technical AEO signals and tracks those scores over time. Architecture helps, but content and ongoing work still matter.</p>`) },
  { q: "Can we keep Webflow if it is working for us?", a: wrap(`<p>Yes. ZINC recommends the approach that fits the business. That may mean improving the current Webflow site, introducing selected AI-assisted workflows, or planning a move when the benefits justify it. Migration is a decision, not a requirement.</p><a class="faq-link" href="/solutions/enterprise-websites">Explore Enterprise Websites &amp; CMS &gt;</a>`) },
];
