import type { FaqItem } from "@/components/site/faq";

// Answers are our own trusted static content (rendered via innerHTML).
export const FAQ_ITEMS: FaqItem[] = [
  { q: "Will our site still look the same?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>Yes. Migration moves the site you have, page for page, and we verify the design at representative pages and viewports before cutover. You can change the look afterward if you want to, but that is a separate decision, not part of the move.</p></div></div>` },
  { q: "What happens to our blog, images, PDFs, and URLs?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>They come with you. Posts, media, and documents are migrated into your new repository, and every URL is preserved or mapped with a redirect that we verify against the live site. Search equity is monitored after launch so nothing slips unnoticed.</p></div></div>` },
  { q: "How will we edit content, and do we need coding experience?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>No coding experience is required. Your team asks the site&#x27;s AI agent for a change in plain language, previews the result on its own branch, and approves it through Dispatch. Developers can still work in the repository directly whenever they prefer.</p></div></div>` },
  { q: "Can we keep HubSpot, our CRM, forms, and analytics?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>Yes. Forms, CRM delivery, analytics tags, consent tools, and site search are inventoried before cutover, and each one gets an agreed replacement, an owner, and a test. Nothing your business depends on is dropped without a decision.</p></div></div>` },
  { q: "What needs human approval?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>That is up to you. Dispatch roles and risk tiers decide which changes publish on approval and which need a second set of eyes, so a copy fix and a navigation change can follow different rules. Every change is recorded with who asked and who approved.</p></div></div>` },
  { q: "What can be restored, and what happens to submitted data?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>One-click restore covers the site&#x27;s code and deployment, so any published change can be rolled back. Submitted forms, sent email, and other external actions are handled separately by the systems that received them, and we set up those integrations so records land where your team expects.</p></div></div>` },
  { q: "Who owns the code, hosting account, domain, and content?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>You do. The code lives in your own repository, the hosting account and domain stay in your name, and the content is yours. Turn Dispatch off and the website keeps running.</p></div></div>` },
  { q: "Can we use AI without leaving WordPress?", a: `<div class="margin-bottom margin-small"><div class="max-width-large"><p>Often, yes. That is the Enable path: we set up an AI workflow inside WordPress for teams whose CMS is working for them. Migration is the right move when the CMS itself is the constraint, and the free preview tells you which one fits.</p></div></div>` },
];
